### ISSUE TITLE
unnecessary Call Log permission!

### ISSUE THREAD

**Issue by softhive** [Hepolise/CallRecordingEnablerForOOS#3]
You should remove the unnecessary Call Log permission from the app's manifest because of it's unsafe and not affecting the core functionality.

**Comment by Hepolise** [comment]
As I understand both permissions (android.permission.READ_PHONE_STATE and android.permission.PROCESS_OUTGOING_CALLS) are required: https://stackoverflow.com/a/49896735

**Comment by softhive** [comment]
That's not right according Google policy https://www.xda-developers.com/google-play-developer-policy-call-log-sms/
I have tested your app with Call Logs permission disabled, and it works fine on Android Pie.
PS: https://support.google.com/googleplay/android-developer/answer/9047303?hl=en
![Screenshot_20190720-040629](https://user-images.githubusercontent.com/51112364/61568196-18dce900-aaa4-11e9-8710-48aa2cbcf1dd.jpg)

**Comment by Hepolise** [comment]
Permission removed.
